# Generated by Django 2.2 on 2019-04-14 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sptApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExternalQuizStatic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quizName', models.CharField(default='Quiz Default', max_length=250)),
                ('quizScore', models.IntegerField(default=0)),
                ('question1', models.CharField(default='Question1', max_length=250)),
                ('question1answer1', models.CharField(default='Question1 Answer1', max_length=250)),
                ('question1answer2', models.CharField(default='Question1 Answer2', max_length=250)),
                ('question1answer3', models.CharField(default='Question1 Answer3', max_length=250)),
                ('question1answer4', models.CharField(default='Question1 Answer4', max_length=250)),
                ('correctIndex1', models.IntegerField(default=1)),
                ('isCorrectAnswer1', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='ExternalSitesList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('website_name', models.CharField(default='Site 1', max_length=250)),
                ('website_nickname', models.CharField(default='Site 1', max_length=250)),
                ('is_website_used', models.BooleanField(default=False)),
            ],
        ),
        migrations.RemoveField(
            model_name='quizquestion',
            name='external_url',
        ),
    ]
