# Generated by Django 2.2.7 on 2020-05-22 17:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sptApp', '0002_auto_20200514_2223'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quiz',
            name='allow_submissions',
        ),
    ]
