# Generated by Django 2.2.7 on 2020-05-22 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sptApp', '0003_remove_quiz_allow_submissions'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studenttoquizquestion',
            name='grade',
        ),
        migrations.AddField(
            model_name='studenttoquizquestion',
            name='correct',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='studenttoquizquestion',
            name='num_submissions',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='studenttoquizquestion',
            name='submitted_answer',
            field=models.CharField(default='', max_length=512),
        ),
    ]
