# Generated by Django 2.2.7 on 2020-05-23 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sptApp', '0004_auto_20200522_1637'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studenttotopic',
            name='competency',
            field=models.IntegerField(choices=[(0, 'Incomplete'), (1, 'Competency'), (2, 'Mastery')], default=0),
        ),
    ]
