# Generated by Django 2.2.7 on 2020-05-23 21:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sptApp', '0006_auto_20200523_1551'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ExternalQuizStatic',
        ),
        migrations.DeleteModel(
            name='ExternalSitesList',
        ),
        migrations.AlterUniqueTogether(
            name='externalsitetocourse',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='externalsitetocourse',
            name='course',
        ),
        migrations.RemoveField(
            model_name='externalsitetocourse',
            name='external_site',
        ),
        migrations.RemoveField(
            model_name='externalsitetograde',
            name='external_site_to_course',
        ),
        migrations.RemoveField(
            model_name='externalsitetograde',
            name='grade',
        ),
        migrations.RemoveField(
            model_name='grade',
            name='student',
        ),
        migrations.RemoveField(
            model_name='grade',
            name='topic_to_category',
        ),
        migrations.RemoveField(
            model_name='topictocategory',
            name='category',
        ),
        migrations.RemoveField(
            model_name='topictocategory',
            name='topic',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.DeleteModel(
            name='ExternalSite',
        ),
        migrations.DeleteModel(
            name='ExternalSiteToCourse',
        ),
        migrations.DeleteModel(
            name='ExternalSiteToGrade',
        ),
        migrations.DeleteModel(
            name='Grade',
        ),
        migrations.DeleteModel(
            name='TopicToCategory',
        ),
    ]
