# Generated by Django 2.2.7 on 2020-05-24 03:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sptApp', '0008_auto_20200523_1940'),
    ]

    operations = [
        migrations.AlterField(
            model_name='competencythreshold',
            name='course',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='sptApp.Course'),
        ),
        migrations.AlterField(
            model_name='gradethreshold',
            name='course',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='sptApp.Course'),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='assignment',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='quiz_assignment', to='sptApp.Assignment'),
        ),
        migrations.AlterField(
            model_name='settings',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='studenttoquiz',
            name='student_to_assignment',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='quiz_assignment', to='sptApp.StudentToAssignment'),
        ),
    ]
