# Generated by Django 2.2.7 on 2020-05-24 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sptApp', '0009_auto_20200523_2358'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='allow_resubmissions',
            field=models.BooleanField(default=True),
        ),
    ]
