# Generated by Django 3.1.5 on 2021-01-18 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sptApp', '0010_quiz_allow_resubmissions'),
    ]

    operations = [
        migrations.AddField(
            model_name='studenttocourse',
            name='letterGrade',
            field=models.CharField(default='?', max_length=2),
        ),
    ]
