# Generated by Django 3.1.5 on 2021-03-25 16:33

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sptApp', '0012_course_grades_updated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='weight',
            field=models.FloatField(blank=True, default=0, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
