# Generated by Django 3.1.5 on 2021-03-25 17:46

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sptApp', '0013_auto_20210325_1233'),
    ]

    operations = [
        migrations.AlterField(
            model_name='competencythreshold',
            name='competency_threshold',
            field=models.FloatField(blank=True, default=1, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='competencythreshold',
            name='mastery_threshold',
            field=models.FloatField(blank=True, default=2, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
