# Generated by Django 3.2.7 on 2021-11-17 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sptApp', '0014_auto_20210325_1346'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='published',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='pool',
            field=models.CharField(default='{"multiple_choice": 0, "multiple_select": 0, "free_response": 0, "implementation": 0, "execution": 0}', max_length=2048),
        ),
        migrations.AlterField(
            model_name='quizquestion',
            name='question_type',
            field=models.IntegerField(choices=[(0, 'multiple_choice'), (1, 'multiple_select'), (2, 'free_response'), (3, 'implementation'), (4, 'execution')]),
        ),
    ]
