# Generated by Django 3.1.5 on 2021-04-22 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sptApp', '0014_auto_20210325_1346'),
    ]

    operations = [
        migrations.AddField(
            model_name='settings',
            name='public_leaderboard',
            field=models.BooleanField(default=False),
        ),
    ]
