# Generated by Django 3.2.7 on 2021-12-15 00:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sptApp', '0015_auto_20211117_1530'),
    ]

    operations = [
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('section_code', models.CharField(max_length=250)),
                ('course', models.ForeignKey(blank=True, default='0', on_delete=django.db.models.deletion.CASCADE, related_name='course', to='sptApp.course')),
            ],
        ),
        migrations.CreateModel(
            name='StudentToSection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semester', models.CharField(blank=True, max_length=250, null=True)),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='sptApp.section')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_section', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
