# Generated by Django 3.1.5 on 2021-04-22 16:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sptApp', '0015_settings_public_leaderboard'),
    ]

    operations = [
        migrations.CreateModel(
            name='Helper',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('topic_node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sptApp.topic')),
            ],
        ),
        migrations.CreateModel(
            name='Helpee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('topic_node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sptApp.topic')),
            ],
        ),
    ]
