# Generated by Django 3.2.7 on 2022-03-16 20:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sptApp', '0018_quiz_published'),
    ]

    operations = [
        migrations.AddField(
            model_name='section',
            name='frequency',
            field=models.IntegerField(choices=[(0, 'Once'), (1, 'Daily'), (7, 'Weekly'), (14, 'Biweekly')], default=0),
        ),
        migrations.AddField(
            model_name='section',
            name='next_open_date',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='section',
            name='open_duration',
            field=models.IntegerField(default=30),
        ),
    ]
