version: '3'

services:
  nginx:
    image: nginx:1.15-alpine
    restart: unless-stopped
    volumes:
      - ./certificate_data/nginx:/etc/nginx/conf.d
      - ./certificate_data/certbot/conf:/etc/letsencrypt
      - ./certificate_data/certbot/www:/var/www/certbot
      - ./entrypoint:/temp
    ports:
      - "80:80"
      - "443:443"
    env_file:
      - ./config/deployment_vars
    entrypoint: /temp/nginx-entrypoint.sh
    command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"
  certbot:
    image: certbot/certbot
    restart: unless-stopped
    volumes:
      - ./certificate_data/certbot/conf:/etc/letsencrypt
      - ./certificate_data/certbot/www:/var/www/certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"
