### dwp7kp course 2 info
GET http://spt-acas.com:8000/api/student/course/?courseId=2&view_as=
content-type: application/json

### all dwp7kp courses
GET http://spt-acas.com:8000/api/student/course/
content-type: application/json

###