version: '3.7'

services:
  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: F3AoAmWH62GFfFDRejXBh*TVnoJPECMCZHM
    volumes:
      - ./db:/var/lib/postgresql/data
  backend:
    image: python:3
    environment:
      - PYTHONUNBUFFERED=1
    volumes:
      - ./backend:/code
    ports:
      - '8000:8000'
      - '5432:5432'
    links:
      - db:the_db
    command: >
      bash -c "cd ./code
      && pip install --upgrade -r requirements.txt
      && python manage.py makemigrations sptApp
      && python manage.py migrate sptApp
      && python manage.py makemigrations
      && python manage.py migrate
      && python manage.py runserver 0.0.0.0:8000"
  frontend:
    image: 'node:8.11'
    user: 'root'
    environment:
      - NODE_ENV=development
    links:
      - backend:backend-api
    volumes:
      - ./frontend:/app
    ports:
      - '80:5000'
    command: >
      bash -c "cd ./app
      && npm install
      && npm install -g serve
      && npm run build
      && serve -s dist"
